spring.application.name=messenger_2025
spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.globally_quoted_identifiers=true


server.port=8080
server.address=0.0.0.0

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXP}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWK_SET_URL}
spring.security.oauth2.resourceserver.jwt.audience=${JWT_AUDIENCE}

